---
- name: Report | Create report directory
  ansible.builtin.file:
    name: "{{ _reports_host_directory | dirname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: no
  run_once: yes

- name: Report | Create host structure
  ansible.builtin.file:
    name: "{{ _reports_host_directory }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: no

- name: "Report | Generate"
  ansible.builtin.include_tasks:
    file: "report/generate_directories_{{ _format }}.yml"
    apply:
      vars:
        __content: "{{ than_host_indicator_findings | selectattr('metadata.techniques', 'contains', item) }}"
        __dest: "{{ _reports_host_directory }}"
        __loop: "{{ than_host_indicator_findings | map(attribute='metadata') | map(attribute='techniques') | flatten | unique }}"
  loop: "{{ [than_report_format] | flatten }}"
  loop_control:
    loop_var: '_format'


...
