---
- name: Generate YAML
  ansible.builtin.copy:
    content: "{{ __content | to_nice_yaml }}"
    dest: "{{ __dest }}/{{ item }}.yaml"
  loop: "{{ __loop }}"
  delegate_to: localhost
  become: no

...
